package metrick

import (
	"time"
)

const (
	CONST_MEMBERS_YEAR = 12.0
	CONST_MEMBERS_MONTH = 31.0
	CONST_MEMBERS_DAY = 24
	CONST_MEMBERS_HOUR = 60
	CONST_MEMBERS_MINUTE = 60

	CONST_SECTIONS_DAY = 4
	CONST_SECTIONS_QDAY = 6
	CONST_SECTIONS_HOUR = 4
	CONST_SECTIONS_QHOUR = 15
	CONST_SECTIONS_MINUTE = 4
	CONST_SECTIONS_QMINUTE = 15

	CONST_STREAM_DELIMITER byte = 0x0A

	CONST_BUFFER_HOURS = 2

	CONST_BACKUP_OFFSET = -15 * time.Minute
)
